Check CNS update

diff --git a/.pipelines/cni/cilium/cilium-overlay-load-test-template.yaml b/.pipelines/cni/cilium/cilium-overlay-load-test-template.yaml
--- a/.pipelines/cni/cilium/cilium-overlay-load-test-template.yaml
+++ b/.pipelines/cni/cilium/cilium-overlay-load-test-template.yaml
@@ -9,58 +9,58 @@ parameters:
 
 stages:
 
-  - stage: createAKScluster
-    dependsOn: ${{ parameters.dependsOn }}
-    displayName: "AKS Cluster with Cilium"
-    jobs:
-      - job: create_aks_cluster_with_${{ parameters.name }}
-        steps:
-          - template: ../load-test-templates/create-cluster-template.yaml
-            parameters:
-              clusterType: ${{ parameters.clusterType }}
-              clusterName: ${{ parameters.clusterName }}
-              nodeCount: ${{ parameters.nodeCount }}
-              vmSize: ${{ parameters.vmSize }}
-  - stage: install_cilium
-    dependsOn: createAKScluster
-    displayName: "Install Cilium on AKS Overlay"
-    jobs:
-      - job: deploy_cilium_components
-        steps:
-          - task: AzureCLI@1
-            displayName: "Install Cilium, CNS, and ip-masq-agent"
-            inputs:
-              azureSubscription: $(TEST_SUB_SERVICE_CONNECTION)
-              scriptLocation: "inlineScript"
-              scriptType: "bash"
-              addSpnToEnvironment: true
-              inlineScript: |
-                set -ex
-                az extension add --name aks-preview
-                make -C ./hack/swift set-kubeconf AZCLI=az CLUSTER=${{ parameters.clusterName }}-$(make revision)
-                ls -lah
-                pwd
-                kubectl cluster-info
-                kubectl get po -owide -A
-                echo "Deploy Azure-CNS"
-                kubectl apply -f test/integration/manifests/cilium/cns-write-ovly.yaml
-                echo "deploy Cilium ConfigMap"
-                kubectl apply -f cilium/configmap.yaml
-                kubectl apply -f test/integration/manifests/cilium/cilium-config.yaml
-                echo "install Cilium onto Overlay Cluster"
-                kubectl apply -f test/integration/manifests/cilium/cilium-agent
-                kubectl apply -f test/integration/manifests/cilium/cilium-operator
-                # Passes Cilium image to daemonset and deployment
-                envsubst '${CILIUM_VERSION_TAG},${CILIUM_IMAGE_REGISTRY}' < test/integration/manifests/cilium/daemonset.yaml | kubectl apply -f -
-                envsubst '${CILIUM_VERSION_TAG},${CILIUM_IMAGE_REGISTRY}' < test/integration/manifests/cilium/deployment.yaml | kubectl apply -f -
-                kubectl get po -owide -A
-                echo "deploy ip-masq-agent for overlay"
-                kubectl create -f test/integration/manifests/ip-masq-agent/ip-masq-agent.yaml --validate=false
-                cd test/integration/manifests/ip-masq-agent/
-                kubectl create configmap config-custom.yaml
-                kubectl create configmap config-reconcile.yaml
-                cd ../../../..
-                kubectl get po -owide -A
+  # - stage: createAKScluster
+  #   dependsOn: ${{ parameters.dependsOn }}
+  #   displayName: "AKS Cluster with Cilium"
+  #   jobs:
+  #     - job: create_aks_cluster_with_${{ parameters.name }}
+  #       steps:
+  #         - template: ../load-test-templates/create-cluster-template.yaml
+  #           parameters:
+  #             clusterType: ${{ parameters.clusterType }}
+  #             clusterName: ${{ parameters.clusterName }}
+  #             nodeCount: ${{ parameters.nodeCount }}
+  #             vmSize: ${{ parameters.vmSize }}
+  # - stage: install_cilium
+  #   dependsOn: createAKScluster
+  #   displayName: "Install Cilium on AKS Overlay"
+  #   jobs:
+  #     - job: deploy_cilium_components
+  #       steps:
+  #         - task: AzureCLI@1
+  #           displayName: "Install Cilium, CNS, and ip-masq-agent"
+  #           inputs:
+  #             azureSubscription: $(TEST_SUB_SERVICE_CONNECTION)
+  #             scriptLocation: "inlineScript"
+  #             scriptType: "bash"
+  #             addSpnToEnvironment: true
+  #             inlineScript: |
+  #               set -ex
+  #               az extension add --name aks-preview
+  #               make -C ./hack/swift set-kubeconf AZCLI=az CLUSTER=${{ parameters.clusterName }}-$(make revision)
+  #               ls -lah
+  #               pwd
+  #               kubectl cluster-info
+  #               kubectl get po -owide -A
+  #               echo "Deploy Azure-CNS"
+  #               kubectl apply -f test/integration/manifests/cilium/cns-write-ovly.yaml
+  #               echo "deploy Cilium ConfigMap"
+  #               kubectl apply -f cilium/configmap.yaml
+  #               kubectl apply -f test/integration/manifests/cilium/cilium-config.yaml
+  #               echo "install Cilium onto Overlay Cluster"
+  #               kubectl apply -f test/integration/manifests/cilium/cilium-agent
+  #               kubectl apply -f test/integration/manifests/cilium/cilium-operator
+  #               # Passes Cilium image to daemonset and deployment
+  #               envsubst '${CILIUM_VERSION_TAG},${CILIUM_IMAGE_REGISTRY}' < test/integration/manifests/cilium/daemonset.yaml | kubectl apply -f -
+  #               envsubst '${CILIUM_VERSION_TAG},${CILIUM_IMAGE_REGISTRY}' < test/integration/manifests/cilium/deployment.yaml | kubectl apply -f -
+  #               kubectl get po -owide -A
+  #               echo "deploy ip-masq-agent for overlay"
+  #               kubectl create -f test/integration/manifests/ip-masq-agent/ip-masq-agent.yaml --validate=false
+  #               cd test/integration/manifests/ip-masq-agent/
+  #               kubectl create configmap config-custom.yaml
+  #               kubectl create configmap config-reconcile.yaml
+  #               cd ../../../..
+  #               kubectl get po -owide -A
   - stage: pod_deployment
     dependsOn: install_cilium
     displayName: "Pod Deployment"
@@ -122,7 +122,7 @@ stages:
               addSpnToEnvironment: true
               inlineScript: |
                 set -ex
-                make -C ./hack/swift set-kubeconf AZCLI=az CLUSTER=${{ parameters.clusterName }}-$(make revision)
+                make -C ./hack/swift set-kubeconf AZCLI=az CLUSTER=$(CLUSTER)
             name: "GetCluster"
             displayName: "Get AKS Cluster"
           - script: |
@@ -131,31 +131,31 @@ stages:
             retryCountOnTaskFailure: 6
             name: "CiliumConnectivityTests"
             displayName: "Run Cilium Connectivity Tests"
-  - stage: delete
-    displayName: "Delete Resources"
-    dependsOn:
-      - connectivity_tests
-    jobs:
-      - job: delete_resources
-        steps:
-          - task: AzureCLI@1
-            inputs:
-              azureSubscription: $(TEST_SUB_SERVICE_CONNECTION)
-              scriptLocation: "inlineScript"
-              scriptType: "bash"
-              addSpnToEnvironment: true
-              inlineScript: |
-                set -ex
-                if [ "$(DELETE_RESOURCES)" ]
-                then
-                  echo "Deleting Cluster and resource group"
-                  make -C ./hack/swift set-kubeconf AZCLI=az CLUSTER=${{ parameters.clusterName }}-$(make revision)
-                  make -C ./hack/swift azcfg AZCLI=az REGION=$(LOCATION)
-                  make -C ./hack/swift down AZCLI=az REGION=$(LOCATION) SUB=$(SUBSCRIPTION_ID) CLUSTER=${{ parameters.clusterName }}-$(make revision)
-                  echo "Cluster and resources down"
-                else
-                  echo "Deletion of resources is False"
-                fi
-            name: "CleanUpCluster"
-            displayName: "Cleanup cluster"
-    condition: always()
+  # - stage: delete
+  #   displayName: "Delete Resources"
+  #   dependsOn:
+  #     - connectivity_tests
+  #   jobs:
+  #     - job: delete_resources
+  #       steps:
+  #         - task: AzureCLI@1
+  #           inputs:
+  #             azureSubscription: $(TEST_SUB_SERVICE_CONNECTION)
+  #             scriptLocation: "inlineScript"
+  #             scriptType: "bash"
+  #             addSpnToEnvironment: true
+  #             inlineScript: |
+  #               set -ex
+  #               if [ "$(DELETE_RESOURCES)" ]
+  #               then
+  #                 echo "Deleting Cluster and resource group"
+  #                 make -C ./hack/swift set-kubeconf AZCLI=az CLUSTER=${{ parameters.clusterName }}-$(make revision)
+  #                 make -C ./hack/swift azcfg AZCLI=az REGION=$(LOCATION)
+  #                 make -C ./hack/swift down AZCLI=az REGION=$(LOCATION) SUB=$(SUBSCRIPTION_ID) CLUSTER=${{ parameters.clusterName }}-$(make revision)
+  #                 echo "Cluster and resources down"
+  #               else
+  #                 echo "Deletion of resources is False"
+  #               fi
+  #           name: "CleanUpCluster"
+  #           displayName: "Cleanup cluster"
+  #   condition: always()
